# CRE Project Settings
# Project-level configuration for different deployment targets
# See: https://docs.chain.link/cre/reference/project-configuration

staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

production-settings:
  cre-cli:
    don-family: "zone-a"  # DON family for production deployment
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
